version: '3.3'

# https://docs.docker.com/compose/wordpress/

services:
  db:
    image: mysql:5.7
    ports:
      - 6033:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    # image: wordpress:latest
    build: .
    volumes:
      - ${APP_PATH}:/var/www/html/wp-content
    ports:
      - "8000:80"
    domainname: localhost
    hostname: localhost
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    networks:
      - wpsite
volumes:
  db_data: {}
networks:
  wpsite: